Update README.md
hubreviewapp/hubreviewapp.github.io pull request #2
Opened 2024-02-06 13:33 UTC by AlperMumcular

2024-02-22 20:38 UTC, aysekelleci commented
test

2024-02-25 08:52 UTC, aysekelleci commented
test

2024-02-25 09:46 UTC, aysekelleci commented
<p>testing</p>

2024-02-26 12:12 UTC, aysekelleci commented
<p>test comment</p>

2024-04-08 10:31 UTC, AlperMumcular commented
<!--Using HubReview-->**ACTIVE**: <p>Hello world!</p>

2024-04-08 11:26 UTC, Ece-Kahraman reviewed
yooo

2024-04-08 11:26 UTC, Ece-Kahraman commented on README.md
<!--Using HubReview-->
question(non-blocking): hi

2024-04-08 11:26 UTC, Ece-Kahraman commented on README.md
aaaa

2024-04-08 15:24 UTC, vedxyz requested changes
:basketball:

2024-04-16 21:28 UTC, aysekelleci commented
<!--Using HubReview-->**ACTIVE**: <p>cdvf</p>

2024-04-19 19:23 UTC, aysekelleci commented
<!--Using HubReview-->**ACTIVE**: <p>good job</p>

2024-04-20 12:30 UTC, vIremAydin commented on README.md
<!--Using HubReview-->
none(non-blocking): ömçmömömömömömö

2024-04-20 12:32 UTC, vIremAydin requested changes

2024-04-20 12:32 UTC, vIremAydin commented on README.md
zxcxzczxcxzcxzcxzc

2024-04-20 12:32 UTC, vIremAydin requested changes

2024-04-20 12:32 UTC, vIremAydin commented on README.md
<!--Using HubReview-->
none(non-blocking): kjbjhkhb

2024-04-20 12:51 UTC, vIremAydin commented
<!--Using HubReview-->**ACTIVE**: <p>sś</p>

2024-04-22 11:26 UTC, aysekelleci commented
<!--Using HubReview-->
> 
> **ACTIVE**: <p>csdvv</p>
> https://github.com/hubreviewapp/hubreviewapp.github.io/pull/2#issuecomment-2068057983 

dwefrgt

2024-04-22 11:27 UTC, aysekelleci commented
<!--Using HubReview-->
> 
> **ACTIVE**: <p>ccsdvv</p>
> https://github.com/hubreviewapp/hubreviewapp.github.io/pull/2#issuecomment-2068057983 

deneme

2024-04-22 11:31 UTC, aysekelleci commented
<!--Using HubReview-->
> 
> 
> **ACTIVE**: <p>denemeedb</p>
> https://github.com/hubreviewapp/hubreviewapp.github.io/pull/2#issuecomment-2069152469 

dkldfjf

2024-04-22 11:33 UTC, vIremAydin commented
<!--Using HubReview-->
> **Closed**: <p>Cannot respond to another bot.vdşdv</p>
> https://github.com/hubreviewapp/hubreviewapp.github.io/pull/2#issuecomment-2042617736 

https://github.com/hubreviewapp/hubreviewapp.github.io/pull/2#issuecomment-2042617736

2024-04-23 12:11 UTC, HubReview-tester commented
<!--Using HubReview-->
> <!-- This is an auto-generated reply by CodeRabbit -->
Skipped: Cannot respond to another bot.
> https://github.com/hubreviewapp/hubreviewapp.github.io/pull/2#issuecomment-2069841077 

test reply 1

2024-04-23 12:56 UTC, HubReview-tester commented
<!--Using HubReview-->
> 
> <!-- This is an auto-generated reply by CodeRabbit -->
Skipped: Cannot respond to another bot.
> https://github.com/hubreviewapp/hubreviewapp.github.io/pull/2#issuecomment-2069841077 

test reply 1
> https://github.com/hubreviewapp/hubreviewapp.github.io/pull/2#issuecomment-2072138751 

test reply 2

2024-04-23 13:23 UTC, closed without merging

2024-04-30 10:11 UTC, aysekelleci reviewed
comment

2024-04-30 10:11 UTC, aysekelleci commented on README.md
> +On systems lacking Adobe Acrobat, `qpdf` may be used to encrypt PDFsss:
<!--Using HubReview-->
none(non-blocking): djkwehfkjhr

2024-05-04 10:27 UTC, vIremAydin commented on README.md
> -On systems lacking Adobe Acrobat, `qpdf` may be used to encrypt PDFs:
<!--Using HubReview-->
none(non-blocking): fdvgrfvfgvf

2024-05-04 10:27 UTC, vIremAydin commented on README.md
<!--Using HubReview-->
none(non-blocking): grtgtrrt

2024-05-06 11:53 UTC, HubReview-tester requested changes
please change problematic lines

2024-05-06 11:53 UTC, HubReview-tester commented on README.md
>  # Replace `[pass]`s with a password
<!--Using HubReview-->
ıssue(blocking): Replace this, may cause security problems

2024-05-13 18:31 UTC, HubReview-tester commented
<!--Using HubReview-->
> **Closed**: <p>Cannot respond to another bot.vdşdv</p>
> https://github.com/hubreviewapp/hubreviewapp.github.io/pull/2#issuecomment-2042617736 

meraba